#!/bin/sh
### BEGIN INIT INFO
# Provides:       iivari-express
# Should-Start:
# Required-Start: $remote_fs
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Simple image randomizer for iivari-client
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="Simple image randomizer"
NAME=iivari-express
PIDDIR=/var/run/
PIDFILE=${PIDDIR}/${NAME}.pid
INSTALLDIR=/opt/iivari-express
USER=iivari

if [ -f /etc/default/$NAME ]
then
        . /etc/default/$NAME
fi

# Gracefully exit if the package or its dependencies have been removed (but not purged).
if [ ! -x ${INSTALLDIR} ]
then
  echo "${INSTALLDIR} not found"
  exit 1
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions


case "$1" in
    start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        if [ "$NODM_ENABLED" = "no" ] || [ "$NODM_ENABLED" = "false" ]
        then
                log_warning_msg "Not starting $NAME because NODM_ENABLED is '$NODM_ENABLED' in /etc/default/$NAME"
        else
                start-stop-daemon --start --oknodo --chuid $USER --pidfile ${PIDFILE} --make-pidfile --background --exec /usr/bin/iivari-express
        fi
        [ "$VERBOSE" != no ] && log_end_msg $?
        ;;
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        start-stop-daemon --stop --pidfile ${PIDFILE} --oknodo --user $USER
        rm -f ${PIDFILE}
        # just make sure it's gone..
        killall -9 node
        [ "$VERBOSE" != no ] && log_end_msg $?
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    *)
        log_success_msg "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac


exit 0
